package com.masai.model;

import java.time.LocalDate;

import jakarta.persistence.*;

@Entity
public class Flat {
	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer flatId; // autogenerated
	private String buildingName; // NoOfRooms:(add validation no should be less than 10)
	private LocalDate date_of_manufacturing; // LocalDate (JSON Format)
	private String facing; // (East, West, Nort, South)
	private Double price;
	private String description;

	public Flat() {
		// TODO Auto-generated constructor stub
	}

	public Flat(Integer flatId, String buildingName, LocalDate date_of_manufacturing, String facing, Double price,
			String description) {
		super();
		this.flatId = flatId;
		this.buildingName = buildingName;
		this.date_of_manufacturing = date_of_manufacturing;
		this.facing = facing;
		this.price = price;
		this.description = description;
	}

	public Integer getFlatId() {
		return flatId;
	}

	public void setFlatId(Integer flatId) {
		this.flatId = flatId;
	}

	public String getBuildingName() {
		return buildingName;
	}

	public void setBuildingName(String buildingName) {
		this.buildingName = buildingName;
	}

	public LocalDate getDate_of_manufacturing() {
		return date_of_manufacturing;
	}

	public void setDate_of_manufacturing(LocalDate date_of_manufacturing) {
		this.date_of_manufacturing = date_of_manufacturing;
	}

	public String getFacing() {
		return facing;
	}

	public void setFacing(String facing) {
		this.facing = facing;
	}

	public Double getPrice() {
		return price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

	public String getDescription() {
		return description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
